name: Init

permissions:
  contents: write
  actions: write

on:
  push:
    branches:
      - main

jobs:
  init:
    if: github.repository != 'gendloop/template-SlidesProject'
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v3

      - name: get-repo-name
        id: get-repo-name
        shell: bash
        run: |
          repo_name=${GITHUB_REPOSITORY#*/}
          echo "reponame=$repo_name" >> $GITHUB_OUTPUT

      - name: replace-README-REPO
        uses: gendloop/replace-str@v1.0.1
        with:
          token: ${{ github.token }}
          path-to-replace: 'docs/README.md'
          replace-to-path: 'README.md'
          str-to-replace: 'REPO'
          replace-to-str: ${{ steps.get-repo-name.outputs.reponame }}

      - name: replace-README-gendloop
        uses: gendloop/replace-str@v1.0.1
        with:
          token: ${{ github.token }}
          path-to-replace: 'README.md'
          replace-to-path: 'README.md'
          str-to-replace: 'gendloop'
          replace-to-str: ${{ github.actor }}

      - name: replace-slides.md
        uses: gendloop/replace-str@v1.0.1
        with:
          token: ${{ github.token }}
          path-to-replace: 'slides.md'
          replace-to-path: 'slides.md'
          str-to-replace: 'template-SlidesProject'
          replace-to-str: ${{ steps.get-repo-name.outputs.reponame }}

      - name: remove-useless
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
          Remove-Item .github\workflows\Init.yml
          Remove-Item docs\README.md

      - name: remove-sync-log
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
          $file = "sync_log.md"
          if(Test-Path $file) {
            Remove-Item $file -Force
            Write-Host "File $file deleted successfully."
          }
          else {
            Write-Host "File $file does not exist."
          }

      - name: remove-useless-files-for-others
        if: ${{ github.actor != 'gendloop' }}
        working-directory: ${{ github.workspace }}
        shell: pwsh
        run: |
          Remove-Item scripts/downloadFilesFromRepo.json
          Remove-Item .github/workflows/Sync_Download.yml
          Remove-Item .github/FUNDING.yml

      - name: git-push
        uses: gendloop/git-push@v1.0.0
        with:
          token: ${{ github.token }}
          commit: "chore: init project"
